---
title: Python as a Skill
author: 'Hunter Stallard'
date: '2020-12-11'
slug: my-first-post
categories: []
tags: []
description: ''
---
#Python
##Why I am unhappy with my current ability. 
Despite, repeated attempts at inserting a small bit of python code in this blog post, I have not been able to get it to run how I want it. I was trying to run the exact same code from class but despite me knowing the code is able to be run, I can't get past this error.

Traceback (most recent call last):
  File "/tmp/RtmpJjxmpT/chunk-code-7fd2725a46b0.txt", line 5, in <module>
    plt.scatter(x,y, color="red", alpha=.5)
  File "/usr/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 3364, in scatter
    ax = gca()
  File "/usr/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 962, in gca
    return gcf().gca(**kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 592, in gcf
    return figure()
  File "/usr/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 539, in figure
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/backend_bases.py", line 171, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 1049, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1828, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display ":0"

I hope that one day I will be able to use python without searching the for the many errors I create on stack overflow. I know that may be nearly  impossible, but I am going to keep the hope alive regardless. Thanks for a great semester Dr.Woodward, once again you've made your class very enjoyable!

```{python}
import numpy as np
import matplotlib.pyplot as plt
x=np.random.normal(0,1,50) #use numpy.random to take random samples
y=np.random.normal(0,1,50)
#plt.scatter(x,y, color="red", alpha=.5)
#plt.xlabel('x label')
#plt.ylabel('y label')
#plt.title('Title')
#plt.show()
 

```





[Link to google](https://www.google.com)